/*
    Generated by Atomist on 05 07 2016 
*/
package com.itb;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.test.context.web.WebAppConfiguration;
import org.springframework.boot.test.SpringApplicationConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

@RunWith(SpringJUnit4ClassRunner.class)
@SpringApplicationConfiguration(classes = CompanyQuoteSenderApplication.class)
@WebAppConfiguration
public class CompanyQuoteSenderApplicationTests {

	@Test
	public void contextLoads() {
	}
}
